# This is a basic workflow to help you get started with Actions

name: bootcamp2020-covid10-app

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./ bootcamp2020-covid19-app.surge.sh --token ${{ secrets.TOKEN }}
 